# Generated by Django 5.2.7 on 2026-05-25 04:49

import App.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigAutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(db_column='nombre_rol', max_length=60)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=200)),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.BigAutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(db_column='correo', max_length=254, unique=True, verbose_name='correo')),
                ('password', models.CharField(db_column='contrasena', max_length=128, verbose_name='contrasena')),
                ('is_active', models.BooleanField(db_column='estado_usuario', default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fecha_registro')),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, to='App.rol')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuario',
            },
            managers=[
                ('objects', App.models.UsuarioManager()),
            ],
        ),
    ]
