# Generated by Django 5.2.7 on 2026-10-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_usuario_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.BigIntegerField(unique=True)),
                ('alertas_nivel', models.BooleanField(default=True)),
                ('suministro', models.BooleanField(default=True)),
                ('calidad', models.BooleanField(default=True)),
                ('consumo_elevado', models.BooleanField(default=True)),
                ('modo_oscuro', models.BooleanField(default=False)),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=2)),
                ('reportes_semanales', models.BooleanField(default=False)),
                ('ultimo_reporte_semanal', models.DateField(blank=True, null=True)),
                ('ultimo_reporte_datos', models.JSONField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'preferencias de usuario',
                'verbose_name_plural': 'preferencias de usuarios',
                'db_table': 'preferencias_usuario',
            },
        ),
    ]
