# Generated by Django 5.2.7 on 2026-09-22 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('consumption_quantile', 'Consumo (cuantiles)'), ('anomaly_detector', 'Detector de anomalías')], max_length=30)),
                ('version', models.CharField(max_length=40)),
                ('file_path', models.CharField(max_length=500)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('feature_names', models.JSONField(blank=True, default=list)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ml_model_artifact',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('source', models.CharField(choices=[('synthetic', 'Sintético'), ('real', 'Dispositivo real (ESP32)')], default='synthetic', max_length=12)),
                ('source_ref_tanque_id', models.BigIntegerField(blank=True, help_text='id_tanque real (tabla tanque) cuando source=real.', null=True)),
                ('capacidad_maxima_litros', models.FloatField(default=10000.0)),
                ('nivel_critico_litros', models.FloatField(default=1500.0)),
                ('forma_geometrica', models.CharField(default='cilindrico', max_length=20)),
                ('altura_total_cm', models.FloatField(default=200.0)),
                ('diametro_cm', models.FloatField(blank=True, null=True)),
                ('largo_cm', models.FloatField(blank=True, null=True)),
                ('ancho_cm', models.FloatField(blank=True, null=True)),
                ('inflow_schedule', models.JSONField(blank=True, default=dict)),
                ('nivel_actual_litros', models.FloatField(default=8000.0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'zona (ML)',
                'verbose_name_plural': 'zonas (ML)',
                'db_table': 'ml_zone',
            },
        ),
        migrations.CreateModel(
            name='ShortagePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('median_hours_to_shortage', models.FloatField(blank=True, null=True)),
                ('p10_hours_to_shortage', models.FloatField(blank=True, null=True)),
                ('p90_hours_to_shortage', models.FloatField(blank=True, null=True)),
                ('probabilidad_desabasto_horizonte', models.FloatField(default=0.0, help_text='Fracción de trayectorias Monte Carlo que cruzan el umbral crítico dentro del horizonte.')),
                ('horizonte_horas', models.PositiveIntegerField(default=72)),
                ('nivel_riesgo', models.CharField(default='bajo', max_length=15)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortage_predictions', to='ml_engine.zone')),
            ],
            options={
                'db_table': 'ml_shortage_prediction',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('synthetic', 'Sintético'), ('real', 'Dispositivo real (ESP32)')], default='synthetic', max_length=12)),
                ('source_ref_vivienda_id', models.BigIntegerField(blank=True, help_text='id_vivienda real (tabla vivienda) cuando source=real. Null para hogares sintéticos.', null=True, unique=True)),
                ('archetype', models.CharField(choices=[('single', 'Ocupante único'), ('couple', 'Pareja'), ('family_small', 'Familia pequeña (3-4)'), ('family_large', 'Familia grande (5+)'), ('irrigation_heavy', 'Uso intensivo de riego'), ('home_office', 'Oficina en casa (uso diurno alto)'), ('low_occupancy', 'Baja ocupación / vacacional')], default='family_small', max_length=20)),
                ('ocupantes', models.PositiveSmallIntegerField(default=3)),
                ('cluster_id', models.PositiveSmallIntegerField(default=0, help_text='Categoría usada como feature del modelo global (no es 1 modelo por hogar).')),
                ('etiqueta', models.CharField(blank=True, max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homes', to='ml_engine.zone')),
            ],
            options={
                'verbose_name': 'hogar (ML)',
                'verbose_name_plural': 'hogares (ML)',
                'db_table': 'ml_home',
            },
        ),
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('presion', 'Presión'), ('flujo', 'Flujo')], max_length=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('ts', models.DateTimeField()),
                ('score', models.FloatField(help_text='Score de anomalía (más negativo/alto = más anómalo, según método).')),
                ('severity', models.CharField(default='media', max_length=10)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='ml_engine.home')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='ml_engine.zone')),
            ],
            options={
                'db_table': 'ml_anomaly_event',
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='ConsumptionAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('hourly', 'Por hora'), ('daily', 'Diario')], default='hourly', max_length=10)),
                ('period_start', models.DateTimeField()),
                ('litros', models.FloatField()),
                ('presion_media', models.FloatField(blank=True, null=True)),
                ('calidad_media', models.FloatField(blank=True, null=True)),
                ('sensor_offline', models.BooleanField(default=False)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumo_agregado', to='ml_engine.home')),
            ],
            options={
                'db_table': 'ml_consumption_aggregate',
                'indexes': [models.Index(fields=['home', 'period', 'period_start'], name='ml_consumpt_home_id_354411_idx')],
                'unique_together': {('home', 'period', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='ConsumptionForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('target_ts', models.DateTimeField(db_index=True)),
                ('horizon', models.CharField(default='hourly', max_length=10)),
                ('p10', models.FloatField()),
                ('p50', models.FloatField()),
                ('p90', models.FloatField()),
                ('explanation', models.JSONField(blank=True, default=dict, help_text='Top SHAP features para esta predicción.')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='ml_engine.home')),
                ('model_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml_engine.modelartifact')),
            ],
            options={
                'db_table': 'ml_consumption_forecast',
                'ordering': ['target_ts'],
                'indexes': [models.Index(fields=['home', 'target_ts'], name='ml_consumpt_home_id_ceb0e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='TankTrajectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('target_ts', models.DateTimeField(db_index=True)),
                ('p10_litros', models.FloatField()),
                ('p50_litros', models.FloatField()),
                ('p90_litros', models.FloatField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajectories', to='ml_engine.zone')),
            ],
            options={
                'db_table': 'ml_tank_trajectory',
                'ordering': ['target_ts'],
                'indexes': [models.Index(fields=['zone', 'target_ts'], name='ml_tank_tra_zone_id_13c9f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('flujo', 'Flujo (L/min)'), ('presion', 'Presión'), ('calidad', 'Calidad (TDS)'), ('nivel_tanque', 'Nivel de tanque (litros)')], max_length=20)),
                ('ts', models.DateTimeField(db_index=True)),
                ('value', models.FloatField()),
                ('is_valid', models.BooleanField(default=True)),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='ml_engine.home')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='ml_engine.zone')),
            ],
            options={
                'verbose_name': 'lectura (ML)',
                'verbose_name_plural': 'lecturas (ML)',
                'db_table': 'ml_sensor_reading',
                'indexes': [models.Index(fields=['home', 'metric', 'ts'], name='ml_sensor_r_home_id_1cfa51_idx'), models.Index(fields=['zone', 'metric', 'ts'], name='ml_sensor_r_zone_id_9855f0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='home',
            index=models.Index(fields=['zone', 'activo'], name='ml_home_zone_id_e2f3b2_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyevent',
            index=models.Index(fields=['home', 'ts'], name='ml_anomaly__home_id_7bbed7_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyevent',
            index=models.Index(fields=['zone', 'ts'], name='ml_anomaly__zone_id_db7239_idx'),
        ),
    ]
