# Generated by Django 5.2.7 on 2026-10-03 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptionaggregate',
            name='anomaly_kind',
            field=models.CharField(blank=True, default='', help_text='Etiqueta del simulador (leak/burst/…) para entrenar predicción de fugas. Vacío en datos reales.', max_length=32),
        ),
        migrations.AlterField(
            model_name='modelartifact',
            name='kind',
            field=models.CharField(choices=[('consumption_quantile', 'Consumo (cuantiles)'), ('anomaly_detector', 'Detector de anomalías'), ('leak_predictor', 'Predictor de fugas')], max_length=30),
        ),
        migrations.CreateModel(
            name='LeakPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('horizonte_horas', models.PositiveIntegerField(default=12)),
                ('probabilidad', models.FloatField(help_text='Probabilidad 0–1 de fuga en el horizonte.')),
                ('nivel_riesgo', models.CharField(default='bajo', max_length=15)),
                ('method', models.CharField(default='heuristic', max_length=20)),
                ('drivers', models.JSONField(blank=True, default=list)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leak_predictions', to='ml_engine.home')),
                ('model_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml_engine.modelartifact')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leak_predictions', to='ml_engine.zone')),
            ],
            options={
                'db_table': 'ml_leak_prediction',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['home', 'generated_at'], name='ml_leak_pre_home_id_3da891_idx'), models.Index(fields=['zone', 'generated_at'], name='ml_leak_pre_zone_id_07bdbe_idx')],
            },
        ),
    ]
