# Generated by Django 5.2.7 on 2026-10-06 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0002_consumptionaggregate_anomaly_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorState',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=20)),
                ('last_summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'ml_monitor_state',
            },
        ),
        migrations.CreateModel(
            name='PredictionJob',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'En curso'), ('done', 'Terminada'), ('error', 'Con error')], default='running', max_length=10)),
                ('step', models.CharField(blank=True, max_length=120)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.BigIntegerField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ml_prediction_job',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='home',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Datos de la vivienda real (NIC, dirección, zona, titular, sensores).'),
        ),
        migrations.AddField(
            model_name='leakprediction',
            name='alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leakprediction',
            name='alerta_id',
            field=models.BigIntegerField(blank=True, help_text='id_alerta creado en Supabase si se generó alerta.', null=True),
        ),
        migrations.AddField(
            model_name='leakprediction',
            name='evaluated_until',
            field=models.DateTimeField(blank=True, help_text='Timestamp de la última lectura analizada.', null=True),
        ),
        migrations.AddField(
            model_name='leakprediction',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='Métricas medidas que sustentan la predicción (para el aviso al admin).'),
        ),
        migrations.AddField(
            model_name='leakprediction',
            name='fuga_id',
            field=models.BigIntegerField(blank=True, help_text='id_fuga creado en Supabase si se generó alerta.', null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Datos del tanque real (nombre, sensor de nivel, umbrales en cm).'),
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reading_ts', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('home', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_state', to='ml_engine.home')),
            ],
            options={
                'db_table': 'ml_sync_state',
            },
        ),
    ]
