# Generated by Django 5.2.7 on 2026-10-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0003_real_data_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortageprediction',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Nivel actual, estado de la bomba y otros datos de la predicción.'),
        ),
    ]
