# Generated by Django 5.2.7 on 2026-10-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0004_shortage_details'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['home', 'ts'], name='ml_sensor_r_home_id_280ffa_idx'),
        ),
    ]
